import type { EventFormData, ParsedEvent } from '../types/event';

const defaultEvent: EventFormData = {
  event_date: '',
  event_type: '',
  assigned_dj: '',
  second_assigned: '',
  system_number: '',
  dj_attire: '',
  venue_name: '',
  venue_address: '',
  venue_phone: '',
  venue_contact: '',
  venue_notes: '',
  ceremony_separate_location: null,
  client_name: '',
  client_phone: '',
  client_email: '',
  partner_phone: '',
  partner_email: '',
  secondary_contact: '',
  bride_name: '',
  groom_name: '',
  bride_parents: '',
  groom_parents: '',
  guest_count: null,
  maid_of_honor: '',
  best_man: '',
  flower_girl: '',
  ring_bearer: '',
  introduction_name: '',
  bridesmaids: [],
  groomsmen: [],
  pickup_time: '',
  setup_time: '',
  guest_arrival_time: '',
  load_in_time: '',
  ceremony_start_time: '',
  ceremony_end_time: '',
  start_time: '',
  end_time: '',
  booked_hours: null,
  dinner_service: '',
  blessing_by: '',
  toasts_by: '',
  take_requests: null,
  introduce_couple: null,
  introduce_wedding_party: null,
  activities: [],
  music_variety: [],
  pay_type: '',
  base_pay: 0,
  compliance_bonus: 0,
  over_hours_pay: 0,
  fuel_recovery: 0,
  tip: 0,
  overtime_pay: 0,
  other_pay: 0,
  timeline: [],
  music_selections: null,
  special_instructions: '',
  notes: '',
  raw_ai_summary: null,
  status: 'upcoming',
};

export function applyParsedData(parsed: ParsedEvent): EventFormData {
  const coupleSummary = parsed.bride_name && parsed.groom_name
    ? `${parsed.bride_name} & ${parsed.groom_name}`
    : parsed.bride_name || parsed.groom_name || null;

  const has_ai_data = parsed.event_date || parsed.venue_name || parsed.event_type ||
    parsed.client_name || parsed.bride_name || parsed.groom_name ||
    parsed.timeline.length > 0;

  return {
    ...defaultEvent,
    event_date: parsed.event_date || '',
    event_type: parsed.event_type || '',
    assigned_dj: parsed.assigned_dj || '',
    second_assigned: parsed.second_assigned || '',
    system_number: parsed.system_number || '',
    dj_attire: parsed.dj_attire || '',
    venue_name: parsed.venue_name || '',
    venue_address: parsed.venue_address || '',
    venue_phone: parsed.venue_phone || '',
    venue_contact: parsed.venue_contact || '',
    venue_notes: parsed.venue_notes || '',
    ceremony_separate_location: parsed.ceremony_separate_location ?? null,
    client_name: parsed.client_name || coupleSummary || '',
    client_phone: parsed.client_phone || '',
    client_email: parsed.client_email || '',
    partner_phone: parsed.partner_phone || '',
    partner_email: parsed.partner_email || '',
    secondary_contact: parsed.secondary_contact || '',
    bride_name: parsed.bride_name || '',
    groom_name: parsed.groom_name || '',
    bride_parents: parsed.bride_parents || '',
    groom_parents: parsed.groom_parents || '',
    guest_count: parsed.guest_count ?? null,
    maid_of_honor: parsed.maid_of_honor || '',
    best_man: parsed.best_man || '',
    flower_girl: parsed.flower_girl || '',
    ring_bearer: parsed.ring_bearer || '',
    introduction_name: parsed.introduction_name || '',
    pickup_time: parsed.pickup_time || '',
    setup_time: parsed.setup_time || '',
    guest_arrival_time: parsed.guest_arrival_time || '',
    load_in_time: parsed.load_in_time || '',
    ceremony_start_time: parsed.ceremony_start_time || '',
    ceremony_end_time: parsed.ceremony_end_time || '',
    start_time: parsed.start_time || '',
    end_time: parsed.end_time || '',
    booked_hours: parsed.booked_hours ?? null,
    dinner_service: parsed.dinner_service || '',
    blessing_by: parsed.blessing_by || '',
    toasts_by: parsed.toasts_by || '',
    take_requests: parsed.take_requests ?? null,
    introduce_couple: parsed.introduce_couple ?? null,
    introduce_wedding_party: parsed.introduce_wedding_party ?? null,
    bridesmaids: parsed.bridesmaids ?? [],
    groomsmen: parsed.groomsmen ?? [],
    activities: parsed.activities ?? [],
    music_variety: parsed.music_variety ?? [],
    timeline: parsed.timeline ?? [],
    music_selections: parsed.music_selections ?? null,
    pay_type: parsed.pay_type || '',
    base_pay: parsed.base_pay || 0,
    compliance_bonus: parsed.compliance_bonus || 0,
    over_hours_pay: parsed.over_hours_pay || 0,
    fuel_recovery: parsed.fuel_recovery || 0,
    tip: parsed.tip || 0,
    overtime_pay: parsed.overtime_pay || 0,
    other_pay: parsed.other_pay || 0,
    special_instructions: parsed.special_instructions || '',
    notes: parsed.notes || '',
    raw_ai_summary: has_ai_data
      ? `${parsed.event_type || 'Event'} – ${coupleSummary || 'TBD'} at ${parsed.venue_name || 'TBD'} on ${parsed.event_date || 'TBD'}`
      : null,
  };
}
